### ISSUE TITLE
URL collected wrong when using express.Router

### ISSUE THREAD

**Issue by KarineValenca** [labbsr0x/express-monitor#11]
When an application uses express.Router() (e.g https://github.com/labbsr0x/bb-bot/blob/master/src/server.js#L147), the express-monitor is collecting the wrong URL from endpoint inside the router. I prepared a simple example to show the problem:

_router.js_
```javascript
var express =  require('express')
var router = express.Router()

router.get('/hello', (req, res) => {
	res.send("hello")
})

module.exports = router
```

server.js
```javascript
...
const router = require('./router')
...
app.use('/router', router)
...
```

When I access the `localhost:3000/router/hello`, the URL being collected and registered in `/metrics` is `/hello` when the right one to be collected should be `/router/hello`. 

I think the problem is here:
https://github.com/labbsr0x/express-monitor/blob/2ccf28de3f6e10486930295fccf5f74ecb78e994/lib/monitor.js#L147

Also here:
https://github.com/labbsr0x/express-monitor/blob/2ccf28de3f6e10486930295fccf5f74ecb78e994/lib/monitor.js#L77

Instead of using `req.url`, using `req.originalUrl` looks more appropriate:
https://expressjs.com/pt-br/api.html#req.originalUrl

<img width="231" alt="Screen Shot 2020-07-23 at 09 20 38" src="https://user-images.githubusercontent.com/8433187/88285619-d016cc00-ccc5-11ea-9378-51c1a1bb6a23.png">

**Comment by eabili0** [comment]
Indeed!
