### ISSUE TITLE
Expose request seconds bucket

### ISSUE THREAD

**Issue by kevynsax** [labbsr0x/express-monitor#27]
In some metrics makes sense to use the request seconds bucket without using the express endpoints.
For example:
If your internal process is triggered by an ampq queue. Your program was requested to proccess something and not by an express endpoint. 

Today the only way to create a *request_seconds* histogram to attend the b5 pattern in this cases is to not use the express-monitor library. Because when some histogram is registered, you can not register the same name.

The way to resolve this problem is exposing this metrics to be called by the library user

I created an pull request proposing one implementation of this solution please fell free to accept as it is or not.

**Comment by eabili0** [comment]
Thank you for you contribution @kevynsax! Fixed by #26
