### ISSUE TITLE
Add suport to swagger-express-middleware

### ISSUE THREAD

**Issue by KarineValenca** [labbsr0x/express-monitor#32]
express-monitor does not work correctly with applications that use the [swagger-express-middleware](https://www.npmjs.com/package/swagger-express-middleware). 

When it tries to capture metrics from a swagger endpoint, the addr label is filled with `"/^(?!\/metrics$).*/"`. The reason is the `req.baseUrl` and `req.route.path` are blank in the swagger route. So, for some reason, the express-monitor considers that the the `req.route.path` is `"/^(?!\/metrics$).*/"`.

I think a good way to solve this issue is to check if the request is a swagger type and if it's the case, collect the address by the `req.swagger.pathName`

**Comment by eabili0** [comment]
@KarineValenca, interesting problem. I agree with your proposed solution.
