### ISSUE TITLE
New parameter in method 'init' to customize URL /metrics

### ISSUE THREAD

**Issue by gerdsonferreira** [labbsr0x/express-monitor#4]
I would like to insert an application context parameter in `init` method to change the metrics export path `/metrics` . 
```js
Monitor.init(app, true, [0.1, 1], "v1.0.0", 'context/metrics', status => {})
```
ex: I will call my endpoint `example.com/context/metrics`

**Comment by eabili0** [comment]
@gerdsonferreira, I just released version v2.2.0 that addresses this issue. I added  the `metricsEndpoint` param **after** the isErrorCallback for compatibility reasons. Thanks!
